-   id: svelte-check
    name: Svelte Check
    description: Runs svelte-check
    entry: npx
    args: ["svelte-check","--tsconfig","./tsconfig.json"]
    language: node
    types: [text]
    additional_dependencies: ["svelte-check@3.1.4"]
    pass_filenames: false
